<a href="https://colab.research.google.com/github/heispv/tf_class/blob/master/01_intro_to_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# tf.constant()

## Scalar
Listi az adad ke faghat yek adad tooshe

In [ ]:
my_scalar = tf.constant(3)
print(type(my_scalar))
print(my_scalar)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(3, shape=(), dtype=int32)


* dtype (datatype) = integer 32 (integer 32 bit)
* numpy = 3


In [ ]:
my_scalar.shape

TensorShape([])

In [ ]:
# biaim va bode tensor emoon ro bebinim
my_scalar.ndim

0

* Ma mitoonim tensorflow object ro be numpy tabdil konim

In [ ]:
# tensorflow ro be numpy tabdil kardam
my_scalar.numpy()

3

## Vector
Listi az adad hast ke yek bod daran

In [ ]:
my_vector = tf.constant([1, 2, 3, 4])
my_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# shape ro bebinim
my_vector.shape

TensorShape([4])

In [ ]:
# bodesh ro bebinim
my_vector.ndim

1

## matrix
matrix lisit az adad hast ke be komake radif va sotoon mitoonim oonaro az ham dge joda konim

In [ ]:
my_matrix = tf.constant([[1, 2, 3],
                         [2, 3, 4],
                         [5, 5, 5]])
my_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [5, 5, 5]], dtype=int32)>

chon matrix e man 2 satr va 3 sotoon dare

In [ ]:
my_matrix.shape

TensorShape([3, 3])

In [ ]:
my_matrix.ndim

2

## Tensor
majmooei az matrix ha ke poshte sare ham gharar gereftan.

In [ ]:
my_tensor = tf.constant([[[1, 2, 3],
                          [3, 4, 3]],

                         [[10, 20, 4],
                          [30, 40, 200]],

                         [[10, 20, 4],
                          [30, 40, 200]]])
my_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  3,   4,   3]],

       [[ 10,  20,   4],
        [ 30,  40, 200]],

       [[ 10,  20,   4],
        [ 30,  40, 200]]], dtype=int32)>

In [ ]:
# shape e tensor ro peyda konim
my_tensor.shape

TensorShape([2, 2, 3])

man 2 ta matrix daram ke har kodoomeshoon 2 dar 3 hastan

pas hamishe shape e tensor ha be soorate `shape(z, n, m)`
yani `z` ta matrix e `n` dar `m` darim

# tf.Variable()

In [ ]:
my_v = tf.Variable([1, 2, 3, 4])
my_v

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# mesal numpy
my_numpy = np.array([1, 2, 3, 4])
my_numpy

array([1, 2, 3, 4])

In [ ]:
my_numpy[1] = 10

In [ ]:
my_numpy

array([ 1, 10,  3,  4])

In [ ]:
my_v[2] = 15

TypeError: ignored

In [ ]:
my_v[2].assign(15)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 1,  2, 15,  4], dtype=int32)>

In [ ]:
# bebinim va tf.constant ham javab mide?
tf.constant[0].assign(40)

TypeError: ignored

* pas yademoon bashe ke agar yek variable be komake tf.constant() besazim gheire ghabele taghir hastesh, ama agar be komake tf.variable() besazim mitoonim badan taghiresh ham bedim.

In [ ]:
my_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  3,   4,   3]],

       [[ 10,  20,   4],
        [ 30,  40, 200]],

       [[ 10,  20,   4],
        [ 30,  40, 200]]], dtype=int32)>

In [ ]:
my_tensor[1][1][2]

<tf.Tensor: shape=(), dtype=int32, numpy=200>

# tf.ones(shape)

In [ ]:
my_ones = tf.ones(shape=(3, 2, 2))
my_ones

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

# tf.zoros(shape)

In [ ]:
my_zeros = tf.zeros(shape=(2, 3, 2))
my_zeros

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
my_zeros.numpy()

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [ ]:
# tabdil e numpy be tensor
matrise_man = np.array([[1, 2, 3],
                        [10, 15, 20]])
matrise_man

array([[ 1,  2,  3],
       [10, 15, 20]])

In [ ]:
matrise_man_tf = tf.constant(matrise_man)
matrise_man_tf

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 1,  2,  3],
       [10, 15, 20]])>

# Tensor Operations

In [ ]:
data = np.array([1, 2, 3])
data_tf = tf.constant(data)
data_tf

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
data_tf + 10

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([11, 12, 13])>

In [ ]:
data_tf * 2

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

In [ ]:
new_data = tf.multiply(data_tf, 2)

In [ ]:
data_tf

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
new_data

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

* pas be in deghat konim ke be komake tf.multiply(a, b) ma dar asl hich kudum az constant haro taghir nadadim, balke javabe oon haro dar yek variable e jadid zakhire kardim.

# tf.matmul(a, b)
mitoonim dota matrix ro dar ham zarb konim.

In [ ]:
new = tf.constant([[1, 2, 3],
                   [3, 4, 3]])
new_2 = tf.constant([[1, 2],
                     [3, 4],
                     [10, 20]])

In [ ]:
answer = tf.matmul(new, new_2)

In [ ]:
answer

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[37, 70],
       [45, 82]], dtype=int32)>

In [ ]:
answer.ndim

2

In [ ]:
new

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 3]], dtype=int32)>

In [ ]:
tf.transpose(new)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [3, 3]], dtype=int32)>

In [ ]:
# az transpose estefade konam va matrix ro dakhele transpose esh zarb konam
tf.matmul(new, tf.transpose(new))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [20, 34]], dtype=int32)>

# tf.reshape(shape)

In [ ]:
example = np.arange(20)
example

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
my_answer = tf.reshape(example, shape=(2, 2, 5))

In [ ]:
my_answer

<tf.Tensor: shape=(2, 2, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])>

# tf.tensordot(a, b)

In [ ]:
matrix_a = tf.constant([[10, 11, 12, 13, 14],
                        [15, 16, 17, 18, 19]])

matrix_b = tf.constant([[ 0,  1,  2,  3,  4],
                        [ 5,  6,  7,  8,  9]])

In [ ]:
matrix_a = tf.constant([[10, 11, 12, 13, 14],
                        [15, 16, 17, 18, 19]])

matrix_b = tf.constant([[ 0,  1,  2,  3,  4],
                        [ 5,  6,  7,  8,  9]])

result = tf.tensordot(matrix_a, tf.transpose(matrix_b))

print(result)

tf.Tensor(
[[130 430]
 [180 605]], shape=(2, 2), dtype=int32)
